version: '3.8'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: intent-processor-front-end:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://back-end:4000
    depends_on:
      - back-end
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: intent-processor-back-end:latest
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M